
import mongoose from "mongoose";
import dotenv from "dotenv";

dotenv.config({ path: ".env.local" });
dotenv.config();

const MONGODB_URI = process.env.MONGODB_URI;

if (!MONGODB_URI) {
  throw new Error("MONGODB_URI is required. Add it in .env.local or environment variables.");
}

const ProductSchema = new mongoose.Schema({}, { strict: false });

const Product = mongoose.model("products", ProductSchema);

function cleanStock(stock) {
  return stock < 0 ? 0 : stock;
}

const products = [

  // ================= MOHINI =================

  {
    name: "Mohini 10/-",
    company: "Mohini",
    mrp: 120,
    offerPrice: 110,
    stock: cleanStock(-49),
    unit: "Packet",
    category: "Tea",
    minQty: 1,
    orderStep: 1,
    isFeatured: false,
  },

  {
    name: "Mohini 5/-",
    company: "Mohini",
    mrp: 60,
    offerPrice: 55,
    stock: cleanStock(-168),
    unit: "Packet",
    category: "Tea",
    minQty: 1,
    orderStep: 1,
    isFeatured: false,
  },

  {
    name: "Mohini Chai 250g",
    company: "Mohini",
    mrp: 180,
    offerPrice: 175,
    stock: cleanStock(18),
    unit: "Packet",
    category: "Tea",
    minQty: 1,
    orderStep: 1,
    isFeatured: true,
  },

  // ================= COLGATE =================

  {
    name: "Civaka 10/-",
    company: "Colgate",
    mrp: 190,
    offerPrice: 181.16,
    stock: cleanStock(-149),
    unit: "Tube",
    category: "Oral Care",
    minQty: 1,
    orderStep: 1,
    isFeatured: false,
  },

  {
    name: "Colgate Strong 200g 130/-",
    company: "Colgate",
    mrp: 120,
    offerPrice: 113.41,
    stock: cleanStock(-29),
    unit: "Tube",
    category: "Oral Care",
    minQty: 1,
    orderStep: 1,
    isFeatured: true,
  },

  {
    name: "Colgete Brush 123",
    company: "Colgate",
    mrp: 80,
    offerPrice: 67,
    stock: cleanStock(24),
    unit: "Piece",
    category: "Oral Care",
    minQty: 1,
    orderStep: 1,
    isFeatured: true,
  },

  // ================= BRITANNIA =================

  {
    name: "50-50 Golmaal",
    company: "Britannia",
    mrp: 920,
    offerPrice: 885,
    stock: cleanStock(0.5),
    unit: "Packet",
    category: "Biscuits",
    minQty: 1,
    orderStep: 1,
    isFeatured: false,
  },

  {
    name: "Britania rusk 50/-",
    company: "Britannia",
    mrp: 1380,
    offerPrice: 1325,
    stock: cleanStock(4.5),
    unit: "Packet",
    category: "Rusk",
    minQty: 1,
    orderStep: 1,
    isFeatured: true,
  },

  {
    name: "Good day 10/-",
    company: "Britannia",
    mrp: 740,
    offerPrice: 715,
    stock: cleanStock(-17),
    unit: "Packet",
    category: "Biscuits",
    minQty: 1,
    orderStep: 1,
    isFeatured: false,
  },

  // ================= DABUR =================

  {
    name: "Dabur Honey 70/-",
    company: "Dabur",
    mrp: 55,
    offerPrice: 51.47,
    stock: cleanStock(69),
    unit: "Bottle",
    category: "Healthcare",
    minQty: 1,
    orderStep: 1,
    isFeatured: true,
  },

  {
    name: "Red Powder 10/-",
    company: "Dabur",
    mrp: 100,
    offerPrice: 95.27,
    stock: cleanStock(104),
    unit: "Packet",
    category: "Oral Care",
    minQty: 1,
    orderStep: 1,
    isFeatured: true,
  },

  {
    name: "Gulab Jal 16/-",
    company: "Dabur",
    mrp: 13.5,
    offerPrice: 12.2,
    stock: cleanStock(282),
    unit: "Bottle",
    category: "Beauty",
    minQty: 1,
    orderStep: 1,
    isFeatured: true,
  },

  // ================= RHM =================

  {
    name: "RHM Haldi 5/-",
    company: "RHM",
    mrp: 120,
    offerPrice: 111,
    stock: cleanStock(42),
    unit: "Packet",
    category: "Masala",
    minQty: 1,
    orderStep: 1,
    isFeatured: true,
  },

  {
    name: "RHM Mircha 10/-",
    company: "RHM",
    mrp: 105,
    offerPrice: 95,
    stock: cleanStock(17),
    unit: "Packet",
    category: "Masala",
    minQty: 1,
    orderStep: 1,
    isFeatured: false,
  },

  {
    name: "Super Garam Masala 200g 390/-",
    company: "RHM",
    mrp: 355,
    offerPrice: 309,
    stock: cleanStock(18),
    unit: "Packet",
    category: "Masala",
    minQty: 1,
    orderStep: 1,
    isFeatured: true,
  },

  // ================= PNG =================

  {
    name: "Ariel 1kg",
    company: "PNG",
    mrp: 122,
    offerPrice: 109,
    stock: cleanStock(18),
    unit: "Packet",
    category: "Detergent",
    minQty: 1,
    orderStep: 1,
    isFeatured: true,
  },

  {
    name: "Gillette Machine 25/-",
    company: "PNG",
    mrp: 200,
    offerPrice: 155,
    stock: cleanStock(14),
    unit: "Piece",
    category: "Shaving",
    minQty: 1,
    orderStep: 1,
    isFeatured: false,
  },

  // ================= NANDAN =================

  {
    name: "Bikaneri toast 10/-",
    company: "Nandan Bakery",
    mrp: 260,
    offerPrice: 235.3,
    stock: cleanStock(15),
    unit: "Packet",
    category: "Bakery",
    minQty: 1,
    orderStep: 1,
    isFeatured: true,
  },

  {
    name: "Rise toast 10/-",
    company: "Nandan Bakery",
    mrp: 190,
    offerPrice: 180,
    stock: cleanStock(10),
    unit: "Packet",
    category: "Bakery",
    minQty: 1,
    orderStep: 1,
    isFeatured: false,
  },

  // ================= BOOMER =================

  {
    name: "Boomer Duet 150/-",
    company: "Boomer",
    mrp: 120,
    offerPrice: 122.3,
    stock: cleanStock(32),
    unit: "Packet",
    category: "Candy",
    minQty: 1,
    orderStep: 1,
    isFeatured: true,
  },

  {
    name: "Snickers chocolate 45/-",
    company: "Boomer",
    mrp: 930,
    offerPrice: 880.62,
    stock: cleanStock(10),
    unit: "Packet",
    category: "Chocolate",
    minQty: 1,
    orderStep: 1,
    isFeatured: true,
  },

  // ================= PATANJALI FOOD =================

  {
    name: "Patanjali Ghee 900g 731/-",
    company: "Patanjali Food",
    mrp: 696.19,
    offerPrice: 667.96,
    stock: cleanStock(11),
    unit: "Jar",
    category: "Ghee",
    minQty: 1,
    orderStep: 1,
    isFeatured: true,
  },

  {
    name: "Sunflower oil 1L 185/-",
    company: "Patanjali Food",
    mrp: 172,
    offerPrice: 163.75,
    stock: cleanStock(20),
    unit: "Bottle",
    category: "Oil",
    minQty: 1,
    orderStep: 1,
    isFeatured: false,
  },

  // ================= PATANJALI NON FOOD =================

  {
    name: "Neem soap 115/-",
    company: "Patanjali Non-Food",
    mrp: 98,
    offerPrice: 86.6,
    stock: cleanStock(22),
    unit: "Packet",
    category: "Soap",
    minQty: 1,
    orderStep: 1,
    isFeatured: true,
  },

  // ADD THESE PRODUCTS INSIDE YOUR products ARRAY

// ================= COLGATE =================

{
  name: "Civaka 69/-",
  company: "Colgate",
  mrp: 58,
  offerPrice: 55.63,
  stock: cleanStock(-514),
  unit: "Tube",
  category: "Oral Care",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Colgate 1/-",
  company: "Colgate",
  mrp: 115,
  offerPrice: 106.81,
  stock: cleanStock(-63),
  unit: "Tube",
  category: "Oral Care",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Colgate Strong 10/-",
  company: "Colgate",
  mrp: 195,
  offerPrice: 192,
  stock: cleanStock(-49),
  unit: "Tube",
  category: "Oral Care",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Colgate strong 100g 70/-",
  company: "Colgate",
  mrp: 63,
  offerPrice: 59.81,
  stock: cleanStock(-126),
  unit: "Tube",
  category: "Oral Care",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Colgate Strong 20/-",
  company: "Colgate",
  mrp: 205,
  offerPrice: 198.54,
  stock: cleanStock(-111),
  unit: "Tube",
  category: "Oral Care",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

// ================= BRITANNIA =================

{
  name: "Good day 40/-",
  company: "Britannia",
  mrp: 36.61,
  offerPrice: 35,
  stock: cleanStock(-1),
  unit: "Packet",
  category: "Biscuits",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Good day 5/-",
  company: "Britannia",
  mrp: 780,
  offerPrice: 764,
  stock: cleanStock(-75),
  unit: "Packet",
  category: "Biscuits",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Marie 5/-",
  company: "Britannia",
  mrp: 795,
  offerPrice: 775,
  stock: cleanStock(-27),
  unit: "Packet",
  category: "Biscuits",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Milk Bikis 5/-",
  company: "Britannia",
  mrp: 720,
  offerPrice: 680,
  stock: cleanStock(-15),
  unit: "Packet",
  category: "Biscuits",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Tiger Biscuit 5/-",
  company: "Britannia",
  mrp: 630,
  offerPrice: 600,
  stock: cleanStock(-49.5),
  unit: "Packet",
  category: "Biscuits",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Tiger Krunch 5/-",
  company: "Britannia",
  mrp: 780,
  offerPrice: 764,
  stock: cleanStock(-27),
  unit: "Packet",
  category: "Biscuits",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Treat chocolate 5/-",
  company: "Britannia",
  mrp: 140,
  offerPrice: 130,
  stock: cleanStock(2),
  unit: "Packet",
  category: "Biscuits",
  minQty: 1,
  orderStep: 1,
  isFeatured: true,
},

// ================= DABUR =================

{
  name: "Anmol Nariyal Tel 10/-",
  company: "Dabur",
  mrp: 105,
  offerPrice: 98.37,
  stock: cleanStock(0),
  unit: "Bottle",
  category: "Hair Oil",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Anmol Nariyal Tel 20/-",
  company: "Dabur",
  mrp: 202,
  offerPrice: 190.72,
  stock: cleanStock(1),
  unit: "Bottle",
  category: "Hair Oil",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Babool 10/-",
  company: "Dabur",
  mrp: 88,
  offerPrice: 74.27,
  stock: cleanStock(37),
  unit: "Tube",
  category: "Oral Care",
  minQty: 1,
  orderStep: 1,
  isFeatured: true,
},

{
  name: "Babool 64/-",
  company: "Dabur",
  mrp: 54,
  offerPrice: 49.96,
  stock: cleanStock(56),
  unit: "Tube",
  category: "Oral Care",
  minQty: 1,
  orderStep: 1,
  isFeatured: true,
},

{
  name: "Dabur Amla 10/-",
  company: "Dabur",
  mrp: 85,
  offerPrice: 78.8,
  stock: cleanStock(63),
  unit: "Bottle",
  category: "Hair Oil",
  minQty: 1,
  orderStep: 1,
  isFeatured: true,
},

{
  name: "Dabur Amla 137/-",
  company: "Dabur",
  mrp: 116,
  offerPrice: 108.76,
  stock: cleanStock(22),
  unit: "Bottle",
  category: "Hair Oil",
  minQty: 1,
  orderStep: 1,
  isFeatured: true,
},

{
  name: "Dabur Honey 24/-",
  company: "Dabur",
  mrp: 200,
  offerPrice: 180,
  stock: cleanStock(5),
  unit: "Bottle",
  category: "Healthcare",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Dabur Honey 45/-",
  company: "Dabur",
  mrp: 37,
  offerPrice: 33.73,
  stock: cleanStock(3),
  unit: "Bottle",
  category: "Healthcare",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Hajmola jeera 10/-",
  company: "Dabur",
  mrp: 185,
  offerPrice: 172,
  stock: cleanStock(12),
  unit: "Packet",
  category: "Digestive",
  minQty: 1,
  orderStep: 1,
  isFeatured: true,
},

{
  name: "Red paste 135/-",
  company: "Dabur",
  mrp: 125,
  offerPrice: 114.32,
  stock: cleanStock(44),
  unit: "Tube",
  category: "Oral Care",
  minQty: 1,
  orderStep: 1,
  isFeatured: true,
},

{
  name: "Sanifresh Cleaner 235/-",
  company: "Dabur",
  mrp: 155,
  offerPrice: 98.45,
  stock: cleanStock(24),
  unit: "Bottle",
  category: "Cleaner",
  minQty: 1,
  orderStep: 1,
  isFeatured: true,
},

// ================= RHM =================

{
  name: "AK dhaniya 500g",
  company: "RHM",
  mrp: 95,
  offerPrice: 85,
  stock: cleanStock(8),
  unit: "Packet",
  category: "Masala",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "AK mircha 500g",
  company: "RHM",
  mrp: 150,
  offerPrice: 130,
  stock: cleanStock(10),
  unit: "Packet",
  category: "Masala",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Chicken masala 5/-",
  company: "RHM",
  mrp: 130,
  offerPrice: 118.74,
  stock: cleanStock(31),
  unit: "Packet",
  category: "Masala",
  minQty: 1,
  orderStep: 1,
  isFeatured: true,
},

{
  name: "Meat Masala 200g",
  company: "RHM",
  mrp: 400,
  offerPrice: 365,
  stock: cleanStock(7),
  unit: "Packet",
  category: "Masala",
  minQty: 1,
  orderStep: 1,
  isFeatured: true,
},

{
  name: "Sendha Namak 1kg 60/-",
  company: "RHM",
  mrp: 50,
  offerPrice: 40,
  stock: cleanStock(36),
  unit: "Packet",
  category: "Salt",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

// ================= PNG =================

{
  name: "365 blade",
  company: "PNG",
  mrp: 200,
  offerPrice: 190,
  stock: cleanStock(-176),
  unit: "Packet",
  category: "Shaving",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "365 Promo",
  company: "PNG",
  mrp: 210,
  offerPrice: 190,
  stock: cleanStock(-1),
  unit: "Packet",
  category: "Shaving",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Ariel 10/-",
  company: "PNG",
  mrp: 480,
  offerPrice: 435,
  stock: cleanStock(-44),
  unit: "Packet",
  category: "Detergent",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Ariel 500g",
  company: "PNG",
  mrp: 61,
  offerPrice: 54.5,
  stock: cleanStock(8),
  unit: "Packet",
  category: "Detergent",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Gillette Cartez 15/-",
  company: "PNG",
  mrp: 115,
  offerPrice: 100,
  stock: cleanStock(19),
  unit: "Piece",
  category: "Shaving",
  minQty: 1,
  orderStep: 1,
  isFeatured: true,
},

{
  name: "H&S Box",
  company: "PNG",
  mrp: 1240,
  offerPrice: 1180,
  stock: cleanStock(-9),
  unit: "Bottle",
  category: "Shampoo",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "H&S lari",
  company: "PNG",
  mrp: 22,
  offerPrice: 20,
  stock: cleanStock(-403),
  unit: "Packet",
  category: "Shampoo",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Tide 1kg 84/-",
  company: "PNG",
  mrp: 67,
  offerPrice: 62,
  stock: cleanStock(24),
  unit: "Packet",
  category: "Detergent",
  minQty: 1,
  orderStep: 1,
  isFeatured: true,
},

{
  name: "Vicks toffee jar",
  company: "PNG",
  mrp: 170,
  offerPrice: 162,
  stock: cleanStock(5),
  unit: "Jar",
  category: "Candy",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Vicks Vaporub 5g",
  company: "PNG",
  mrp: 250,
  offerPrice: 230,
  stock: cleanStock(0),
  unit: "Bottle",
  category: "Healthcare",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Willenson blade",
  company: "PNG",
  mrp: 185,
  offerPrice: 180,
  stock: cleanStock(2),
  unit: "Packet",
  category: "Shaving",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

// ================= NANDAN BAKERY =================

{
  name: "25-25 Toast 20/-",
  company: "Nandan Bakery",
  mrp: 320,
  offerPrice: 300,
  stock: cleanStock(-37),
  unit: "Packet",
  category: "Bakery",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Bakery 250g",
  company: "Nandan Bakery",
  mrp: 520,
  offerPrice: 490,
  stock: cleanStock(-54.5),
  unit: "Packet",
  category: "Bakery",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Bakery jar 140/-",
  company: "Nandan Bakery",
  mrp: 630,
  offerPrice: 586,
  stock: cleanStock(0),
  unit: "Jar",
  category: "Bakery",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Bakery karela",
  company: "Nandan Bakery",
  mrp: 520,
  offerPrice: 500,
  stock: cleanStock(-5),
  unit: "Packet",
  category: "Bakery",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Bakery Namkeen",
  company: "Nandan Bakery",
  mrp: 520,
  offerPrice: 490,
  stock: cleanStock(-25.5),
  unit: "Packet",
  category: "Namkeen",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Bakery Tray 200g",
  company: "Nandan Bakery",
  mrp: 520,
  offerPrice: 490,
  stock: cleanStock(-1),
  unit: "Packet",
  category: "Bakery",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Cream Roll",
  company: "Nandan Bakery",
  mrp: 560,
  offerPrice: 540,
  stock: cleanStock(0),
  unit: "Packet",
  category: "Bakery",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Heeng papdi 1kg",
  company: "Nandan Bakery",
  mrp: 125,
  offerPrice: 115,
  stock: cleanStock(-12),
  unit: "Packet",
  category: "Namkeen",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Jeera Fine 20/-",
  company: "Nandan Bakery",
  mrp: 425,
  offerPrice: 408,
  stock: cleanStock(-55),
  unit: "Packet",
  category: "Namkeen",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Nandan Namkeen 400g",
  company: "Nandan Bakery",
  mrp: 55,
  offerPrice: 50,
  stock: cleanStock(-600),
  unit: "Packet",
  category: "Namkeen",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Nandan Namkeen 900g",
  company: "Nandan Bakery",
  mrp: 114,
  offerPrice: 110,
  stock: cleanStock(-514),
  unit: "Packet",
  category: "Namkeen",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Nandan Namkeen mix 1kg",
  company: "Nandan Bakery",
  mrp: 125,
  offerPrice: 118.75,
  stock: cleanStock(9),
  unit: "Packet",
  category: "Namkeen",
  minQty: 1,
  orderStep: 1,
  isFeatured: true,
},

{
  name: "Nandan Toast 10/-",
  company: "Nandan Bakery",
  mrp: 205,
  offerPrice: 192,
  stock: cleanStock(-565),
  unit: "Packet",
  category: "Bakery",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Nandan Toast 20/-",
  company: "Nandan Bakery",
  mrp: 360,
  offerPrice: 340,
  stock: cleanStock(-419),
  unit: "Packet",
  category: "Bakery",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Navrang 1kg",
  company: "Nandan Bakery",
  mrp: 125,
  offerPrice: 115,
  stock: cleanStock(0),
  unit: "Packet",
  category: "Namkeen",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Navratan 1kg",
  company: "Nandan Bakery",
  mrp: 125,
  offerPrice: 115,
  stock: cleanStock(-12),
  unit: "Packet",
  category: "Namkeen",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

// ================= BOOMER =================

{
  name: "Boomer Blueberry 180/-",
  company: "Boomer",
  mrp: 150,
  offerPrice: 146.77,
  stock: cleanStock(8),
  unit: "Packet",
  category: "Candy",
  minQty: 1,
  orderStep: 1,
  isFeatured: true,
},

{
  name: "Boomer Lolipop 5/-",
  company: "Boomer",
  mrp: 200,
  offerPrice: 176.12,
  stock: cleanStock(8),
  unit: "Packet",
  category: "Candy",
  minQty: 1,
  orderStep: 1,
  isFeatured: true,
},

{
  name: "Boomer Mint 180/-",
  company: "Boomer",
  mrp: 150,
  offerPrice: 146.77,
  stock: cleanStock(18),
  unit: "Packet",
  category: "Candy",
  minQty: 1,
  orderStep: 1,
  isFeatured: true,
},

{
  name: "Boomer orange jelly 160/-",
  company: "Boomer",
  mrp: 135,
  offerPrice: 130.46,
  stock: cleanStock(3),
  unit: "Packet",
  category: "Candy",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Boomer Stick 10/-",
  company: "Boomer",
  mrp: 200,
  offerPrice: 176.12,
  stock: cleanStock(12),
  unit: "Packet",
  category: "Candy",
  minQty: 1,
  orderStep: 1,
  isFeatured: true,
},

{
  name: "Boomer STR 180/-",
  company: "Boomer",
  mrp: 2160,
  offerPrice: 2348.33,
  stock: cleanStock(-0.31),
  unit: "Packet",
  category: "Candy",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Boomer Watermelon 160/-",
  company: "Boomer",
  mrp: 135,
  offerPrice: 130.46,
  stock: cleanStock(6),
  unit: "Packet",
  category: "Candy",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Bounty Bar 45/-",
  company: "Boomer",
  mrp: 525,
  offerPrice: 495.35,
  stock: cleanStock(0),
  unit: "Packet",
  category: "Chocolate",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Bounty Bar 89/-",
  company: "Boomer",
  mrp: 75,
  offerPrice: 72.57,
  stock: cleanStock(1),
  unit: "Packet",
  category: "Chocolate",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Bounty Bar 99/-",
  company: "Boomer",
  mrp: 85,
  offerPrice: 80.72,
  stock: cleanStock(27),
  unit: "Packet",
  category: "Chocolate",
  minQty: 1,
  orderStep: 1,
  isFeatured: true,
},

{
  name: "Bounty Miniature 160/-",
  company: "Boomer",
  mrp: 140,
  offerPrice: 130.46,
  stock: cleanStock(13),
  unit: "Packet",
  category: "Chocolate",
  minQty: 1,
  orderStep: 1,
  isFeatured: true,
},

{
  name: "Double Mint tablet 10/-",
  company: "Boomer",
  mrp: 175,
  offerPrice: 163,
  stock: cleanStock(16),
  unit: "Packet",
  category: "Candy",
  minQty: 1,
  orderStep: 1,
  isFeatured: true,
},

{
  name: "Doublemint Stick 10/-",
  company: "Boomer",
  mrp: 160,
  offerPrice: 146.77,
  stock: cleanStock(22),
  unit: "Packet",
  category: "Candy",
  minQty: 1,
  orderStep: 1,
  isFeatured: true,
},

{
  name: "Galaxy Cookie crumble 100/-",
  company: "Boomer",
  mrp: 85,
  offerPrice: 81.53,
  stock: cleanStock(0),
  unit: "Packet",
  category: "Chocolate",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Galaxy Dark 130/-",
  company: "Boomer",
  mrp: 111.87,
  offerPrice: 106,
  stock: cleanStock(-3),
  unit: "Packet",
  category: "Chocolate",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Galaxy Fruit Nut 100/-",
  company: "Boomer",
  mrp: 87,
  offerPrice: 81.54,
  stock: cleanStock(0),
  unit: "Packet",
  category: "Chocolate",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Galaxy Milk 65/-",
  company: "Boomer",
  mrp: 55,
  offerPrice: 53,
  stock: cleanStock(-7),
  unit: "Packet",
  category: "Chocolate",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Mint Stick 10/-",
  company: "Boomer",
  mrp: 200,
  offerPrice: 176.12,
  stock: cleanStock(7),
  unit: "Packet",
  category: "Candy",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Orbit 10/-",
  company: "Boomer",
  mrp: 170,
  offerPrice: 146.77,
  stock: cleanStock(3),
  unit: "Packet",
  category: "Candy",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Orbit 5/-",
  company: "Boomer",
  mrp: 135,
  offerPrice: 117.41,
  stock: cleanStock(-1),
  unit: "Packet",
  category: "Candy",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Skittles Berry 45/-",
  company: "Boomer",
  mrp: 310,
  offerPrice: 293.54,
  stock: cleanStock(0),
  unit: "Packet",
  category: "Candy",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Skittles Fruits 45/-",
  company: "Boomer",
  mrp: 310,
  offerPrice: 293.54,
  stock: cleanStock(12),
  unit: "Packet",
  category: "Candy",
  minQty: 1,
  orderStep: 1,
  isFeatured: true,
},

{
  name: "Skittles Sour 45/-",
  company: "Boomer",
  mrp: 310,
  offerPrice: 293.54,
  stock: cleanStock(2),
  unit: "Packet",
  category: "Candy",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Snickers Almond 30/-",
  company: "Boomer",
  mrp: 615,
  offerPrice: 587,
  stock: cleanStock(0),
  unit: "Packet",
  category: "Chocolate",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Snickers Berrywish 30/-",
  company: "Boomer",
  mrp: 615,
  offerPrice: 587,
  stock: cleanStock(-0.5),
  unit: "Packet",
  category: "Chocolate",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Snickers Brownie 30/-",
  company: "Boomer",
  mrp: 615,
  offerPrice: 587,
  stock: cleanStock(1.98),
  unit: "Packet",
  category: "Chocolate",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Snickers Butter 30/-",
  company: "Boomer",
  mrp: 615,
  offerPrice: 587,
  stock: cleanStock(4),
  unit: "Packet",
  category: "Chocolate",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Snickers Butterscotch 70/-",
  company: "Boomer",
  mrp: 910,
  offerPrice: 856.16,
  stock: cleanStock(12),
  unit: "Packet",
  category: "Chocolate",
  minQty: 1,
  orderStep: 1,
  isFeatured: true,
},

{
  name: "Snickers chocolate 10/-",
  company: "Boomer",
  mrp: 165,
  offerPrice: 146.77,
  stock: cleanStock(34),
  unit: "Packet",
  category: "Chocolate",
  minQty: 1,
  orderStep: 1,
  isFeatured: true,
},

{
  name: "Snickers chocolate 20/-",
  company: "Boomer",
  mrp: 550,
  offerPrice: 522,
  stock: cleanStock(0),
  unit: "Packet",
  category: "Chocolate",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

// ================= PATANJALI NON-FOOD =================

{
  name: "Aloevera 10/-",
  company: "Patanjali Non-Food",
  mrp: 100,
  offerPrice: 86,
  stock: cleanStock(71),
  unit: "Bottle",
  category: "Healthcare",
  minQty: 1,
  orderStep: 1,
  isFeatured: true,
},

{
  name: "Aloevera 88/-",
  company: "Patanjali Non-Food",
  mrp: 78,
  offerPrice: 60.36,
  stock: cleanStock(6),
  unit: "Bottle",
  category: "Healthcare",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Brush 10/-",
  company: "Patanjali Non-Food",
  mrp: 105,
  offerPrice: 92.12,
  stock: cleanStock(-50),
  unit: "Piece",
  category: "Oral Care",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Dishwash 60/-",
  company: "Patanjali Non-Food",
  mrp: 52,
  offerPrice: 48.8,
  stock: cleanStock(-1),
  unit: "Bottle",
  category: "Cleaner",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Haldi chandan 10/-",
  company: "Patanjali Non-Food",
  mrp: 100,
  offerPrice: 91.27,
  stock: cleanStock(-4),
  unit: "Soap",
  category: "Soap",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Haldi chandan 130/-",
  company: "Patanjali Non-Food",
  mrp: 110,
  offerPrice: 105,
  stock: cleanStock(0),
  unit: "Soap",
  category: "Soap",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Haldi chandan 92/-",
  company: "Patanjali Non-Food",
  mrp: 82,
  offerPrice: 63.11,
  stock: cleanStock(-35),
  unit: "Soap",
  category: "Soap",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Manjan 10/-",
  company: "Patanjali Non-Food",
  mrp: 90,
  offerPrice: 85.56,
  stock: cleanStock(-50),
  unit: "Tube",
  category: "Oral Care",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Manjan 106/-",
  company: "Patanjali Non-Food",
  mrp: 95,
  offerPrice: 89.23,
  stock: cleanStock(2),
  unit: "Tube",
  category: "Oral Care",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Manjan 20/- 11+1",
  company: "Patanjali Non-Food",
  mrp: 180,
  offerPrice: 170.1,
  stock: cleanStock(25),
  unit: "Tube",
  category: "Oral Care",
  minQty: 1,
  orderStep: 1,
  isFeatured: true,
},

{
  name: "Manjan 295/-",
  company: "Patanjali Non-Food",
  mrp: 263,
  offerPrice: 240,
  stock: cleanStock(19),
  unit: "Tube",
  category: "Oral Care",
  minQty: 1,
  orderStep: 1,
  isFeatured: true,
},

{
  name: "Manjan 56/-",
  company: "Patanjali Non-Food",
  mrp: 585,
  offerPrice: 565,
  stock: cleanStock(-26),
  unit: "Tube",
  category: "Oral Care",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Manjan 63/-",
  company: "Patanjali Non-Food",
  mrp: 650,
  offerPrice: 633.11,
  stock: cleanStock(1.5),
  unit: "Tube",
  category: "Oral Care",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Manjan Advance 90/-",
  company: "Patanjali Non-Food",
  mrp: 77,
  offerPrice: 61.25,
  stock: cleanStock(12),
  unit: "Tube",
  category: "Oral Care",
  minQty: 1,
  orderStep: 1,
  isFeatured: true,
},

{
  name: "Neem soap 10/-",
  company: "Patanjali Non-Food",
  mrp: 100,
  offerPrice: 86,
  stock: cleanStock(3),
  unit: "Soap",
  category: "Soap",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Neem soap 88/-",
  company: "Patanjali Non-Food",
  mrp: 78,
  offerPrice: 60.36,
  stock: cleanStock(20),
  unit: "Soap",
  category: "Soap",
  minQty: 1,
  orderStep: 1,
  isFeatured: true,
},

{
  name: "Tejas Telum 75/-",
  company: "Patanjali Non-Food",
  mrp: 67,
  offerPrice: 56.3,
  stock: cleanStock(7),
  unit: "Bottle",
  category: "Hair Oil",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

// ================= PATANJALI FOOD =================

{
  name: "Aata 5kg 250/-",
  company: "Patanjali Food",
  mrp: 225,
  offerPrice: 214.5,
  stock: cleanStock(0),
  unit: "Packet",
  category: "Atta",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Aloevera juice 206/-",
  company: "Patanjali Food",
  mrp: 171.66,
  offerPrice: 144.14,
  stock: cleanStock(3),
  unit: "Bottle",
  category: "Healthcare",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Amla candy 90/-",
  company: "Patanjali Food",
  mrp: 68,
  offerPrice: 64.5,
  stock: cleanStock(6),
  unit: "Packet",
  category: "Candy",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Black salt 200g 15/-",
  company: "Patanjali Food",
  mrp: 10,
  offerPrice: 9,
  stock: cleanStock(70),
  unit: "Packet",
  category: "Salt",
  minQty: 1,
  orderStep: 1,
  isFeatured: true,
},

{
  name: "Chatpata amla 95/-",
  company: "Patanjali Food",
  mrp: 72,
  offerPrice: 68,
  stock: cleanStock(5),
  unit: "Packet",
  category: "Candy",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Daliya 500g 35/-",
  company: "Patanjali Food",
  mrp: 31.15,
  offerPrice: 29.28,
  stock: cleanStock(75),
  unit: "Packet",
  category: "Food",
  minQty: 1,
  orderStep: 1,
  isFeatured: true,
},

{
  name: "Dhaniya 200g 60/-",
  company: "Patanjali Food",
  mrp: 40,
  offerPrice: 37.59,
  stock: cleanStock(5),
  unit: "Packet",
  category: "Masala",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Haldi 200g 82/-",
  company: "Patanjali Food",
  mrp: 55,
  offerPrice: 51.37,
  stock: cleanStock(5),
  unit: "Packet",
  category: "Masala",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Heeng 10g 30/-",
  company: "Patanjali Food",
  mrp: 530,
  offerPrice: 412.74,
  stock: cleanStock(12),
  unit: "Packet",
  category: "Masala",
  minQty: 1,
  orderStep: 1,
  isFeatured: true,
},

{
  name: "Honey 100g 55/-",
  company: "Patanjali Food",
  mrp: 45.8,
  offerPrice: 35.04,
  stock: cleanStock(77),
  unit: "Bottle",
  category: "Healthcare",
  minQty: 1,
  orderStep: 1,
  isFeatured: true,
},


{
  name: "Honey 250g 110/-",
  company: "Patanjali Food",
  mrp: 91.66,
  offerPrice: 70.09,
  stock: cleanStock(5),
  unit: "Bottle",
  category: "Healthcare",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Mircha 200g 115/-",
  company: "Patanjali Food",
  mrp: 77,
  offerPrice: 72,
  stock: cleanStock(15),
  unit: "Packet",
  category: "Masala",
  minQty: 1,
  orderStep: 1,
  isFeatured: true,
},

{
  name: "Mungfai tel 1L 176/-",
  company: "Patanjali Food",
  mrp: 165,
  offerPrice: 157,
  stock: cleanStock(24),
  unit: "Bottle",
  category: "Oil",
  minQty: 1,
  orderStep: 1,
  isFeatured: true,
},

{
  name: "Navratan Aata 180/-",
  company: "Patanjali Food",
  mrp: 164,
  offerPrice: 154.45,
  stock: cleanStock(2),
  unit: "Packet",
  category: "Atta",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Patanjali Basmati Rice 1kg 130/-",
  company: "Patanjali Food",
  mrp: 108,
  offerPrice: 83.45,
  stock: cleanStock(24),
  unit: "Packet",
  category: "Rice",
  minQty: 1,
  orderStep: 1,
  isFeatured: true,
},

{
  name: "Patanjali Chamanprash 1kg 337/-",
  company: "Patanjali Food",
  mrp: 267,
  offerPrice: 241.43,
  stock: cleanStock(6),
  unit: "Jar",
  category: "Healthcare",
  minQty: 1,
  orderStep: 1,
  isFeatured: true,
},

{
  name: "Patanjali Chamanprash 500g 173/-",
  company: "Patanjali Food",
  mrp: 135,
  offerPrice: 123.94,
  stock: cleanStock(7),
  unit: "Jar",
  category: "Healthcare",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Patanjali Ghee 200g 178/-",
  company: "Patanjali Food",
  mrp: 169.52,
  offerPrice: 164.34,
  stock: cleanStock(23),
  unit: "Jar",
  category: "Ghee",
  minQty: 1,
  orderStep: 1,
  isFeatured: true,
},

{
  name: "Patanjali Ghee 450g 393/-",
  company: "Patanjali Food",
  mrp: 374.28,
  offerPrice: 359.11,
  stock: cleanStock(1),
  unit: "Jar",
  category: "Ghee",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Patanjali Kesar 195/-",
  company: "Patanjali Food",
  mrp: 150,
  offerPrice: 139.7,
  stock: cleanStock(10),
  unit: "Packet",
  category: "Healthcare",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Patanjali mini mogra 5kg",
  company: "Patanjali Food",
  mrp: 250,
  offerPrice: 232,
  stock: cleanStock(8),
  unit: "Packet",
  category: "Atta",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Patanjali Namak 1kg",
  company: "Patanjali Food",
  mrp: 300,
  offerPrice: 260,
  stock: cleanStock(-18),
  unit: "Packet",
  category: "Salt",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Patanjali sendha namak 1kg",
  company: "Patanjali Food",
  mrp: 50,
  offerPrice: 40.36,
  stock: cleanStock(55),
  unit: "Packet",
  category: "Salt",
  minQty: 1,
  orderStep: 1,
  isFeatured: true,
},

{
  name: "Patanjali soyabean 10/-",
  company: "Patanjali Food",
  mrp: 7,
  offerPrice: 6.23,
  stock: cleanStock(96),
  unit: "Packet",
  category: "Oil",
  minQty: 1,
  orderStep: 1,
  isFeatured: true,
},

{
  name: "Pushtahar daliya 50/- 500g",
  company: "Patanjali Food",
  mrp: 44.44,
  offerPrice: 41.83,
  stock: cleanStock(9),
  unit: "Packet",
  category: "Food",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Sabji Masala 100g 65/-",
  company: "Patanjali Food",
  mrp: 45,
  offerPrice: 40.72,
  stock: cleanStock(0),
  unit: "Packet",
  category: "Masala",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Sarso Tel 1L 210/-",
  company: "Patanjali Food",
  mrp: 180,
  offerPrice: 162,
  stock: cleanStock(-85),
  unit: "Bottle",
  category: "Oil",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Sarso Tel 2L 415/-",
  company: "Patanjali Food",
  mrp: 390.27,
  offerPrice: 375.26,
  stock: cleanStock(0),
  unit: "Bottle",
  category: "Oil",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Sarso Tel 5L 1025/-",
  company: "Patanjali Food",
  mrp: 958.46,
  offerPrice: 880,
  stock: cleanStock(4),
  unit: "Bottle",
  category: "Oil",
  minQty: 1,
  orderStep: 1,
  isFeatured: true,
},

{
  name: "Soyabean oil 165/-",
  company: "Patanjali Food",
  mrp: 144,
  offerPrice: 135,
  stock: cleanStock(-124),
  unit: "Bottle",
  category: "Oil",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Til Tel 1L 260/-",
  company: "Patanjali Food",
  mrp: 243,
  offerPrice: 210.23,
  stock: cleanStock(-2),
  unit: "Bottle",
  category: "Oil",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Triphala churan 50/-",
  company: "Patanjali Food",
  mrp: 41.66,
  offerPrice: 36.73,
  stock: cleanStock(-15),
  unit: "Packet",
  category: "Healthcare",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Vermicelli plain 20/-",
  company: "Patanjali Food",
  mrp: 17.8,
  offerPrice: 15.64,
  stock: cleanStock(20),
  unit: "Packet",
  category: "Food",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Vermicelli Rosted 23/-",
  company: "Patanjali Food",
  mrp: 19.5,
  offerPrice: 18,
  stock: cleanStock(132),
  unit: "Packet",
  category: "Food",
  minQty: 1,
  orderStep: 1,
  isFeatured: true,
},

// ================= REMAINING DABUR =================

{
  name: "Anmol Nariyal Tel 115/-",
  company: "Dabur",
  mrp: 90,
  offerPrice: 81.81,
  stock: cleanStock(0),
  unit: "Bottle",
  category: "Hair Oil",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Anmol Nariyal Tel 62/-",
  company: "Dabur",
  mrp: 47,
  offerPrice: 44.1,
  stock: cleanStock(52),
  unit: "Bottle",
  category: "Hair Oil",
  minQty: 1,
  orderStep: 1,
  isFeatured: true,
},

{
  name: "Chameli Tel 25/-",
  company: "Dabur",
  mrp: 114,
  offerPrice: 110.2,
  stock: cleanStock(12),
  unit: "Bottle",
  category: "Hair Oil",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Chameli Tel 50/- 5+1",
  company: "Dabur",
  mrp: 225,
  offerPrice: 216,
  stock: cleanStock(-0.5),
  unit: "Bottle",
  category: "Hair Oil",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Cold Cream 10/-",
  company: "Dabur",
  mrp: 280,
  offerPrice: 250,
  stock: cleanStock(4),
  unit: "Jar",
  category: "Beauty",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Dabur Amla 155/-",
  company: "Dabur",
  mrp: 137,
  offerPrice: 123,
  stock: cleanStock(0),
  unit: "Bottle",
  category: "Hair Oil",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Dabur Amla 20/-",
  company: "Dabur",
  mrp: 175,
  offerPrice: 167.2,
  stock: cleanStock(5),
  unit: "Bottle",
  category: "Hair Oil",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Dabur Amla 207/-",
  company: "Dabur",
  mrp: 187,
  offerPrice: 157,
  stock: cleanStock(8),
  unit: "Bottle",
  category: "Hair Oil",
  minQty: 1,
  orderStep: 1,
  isFeatured: true,
},

{
  name: "Dabur Amla 50/-",
  company: "Dabur",
  mrp: 40,
  offerPrice: 37.6,
  stock: cleanStock(6),
  unit: "Bottle",
  category: "Hair Oil",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Dabur Amla 92/-",
  company: "Dabur",
  mrp: 76,
  offerPrice: 70.8,
  stock: cleanStock(66),
  unit: "Bottle",
  category: "Hair Oil",
  minQty: 1,
  orderStep: 1,
  isFeatured: true,
},

{
  name: "Dabur Chamanprash 240/-",
  company: "Dabur",
  mrp: 195,
  offerPrice: 182.41,
  stock: cleanStock(-3),
  unit: "Jar",
  category: "Healthcare",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Dabur honey 125/-",
  company: "Dabur",
  mrp: 106,
  offerPrice: 98.11,
  stock: cleanStock(16),
  unit: "Bottle",
  category: "Healthcare",
  minQty: 1,
  orderStep: 1,
  isFeatured: true,
},

{
  name: "Gulab Jal 30/-",
  company: "Dabur",
  mrp: 24,
  offerPrice: 22.83,
  stock: cleanStock(19),
  unit: "Bottle",
  category: "Beauty",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Gulab Jal 54/-",
  company: "Dabur",
  mrp: 43.15,
  offerPrice: 41.1,
  stock: cleanStock(22),
  unit: "Bottle",
  category: "Beauty",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Gulabri Body Lotion 10/-",
  company: "Dabur",
  mrp: 185,
  offerPrice: 160.45,
  stock: cleanStock(0),
  unit: "Bottle",
  category: "Beauty",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Gulabri Cold Cream 5/-",
  company: "Dabur",
  mrp: 250,
  offerPrice: 200,
  stock: cleanStock(0),
  unit: "Jar",
  category: "Beauty",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Hajmola cola",
  company: "Dabur",
  mrp: 142,
  offerPrice: 136,
  stock: cleanStock(-36),
  unit: "Packet",
  category: "Digestive",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Hajmola Regular 170/-",
  company: "Dabur",
  mrp: 145,
  offerPrice: 132.7,
  stock: cleanStock(5),
  unit: "Packet",
  category: "Digestive",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Hingoli 120/-",
  company: "Dabur",
  mrp: 95,
  offerPrice: 85.18,
  stock: cleanStock(1),
  unit: "Packet",
  category: "Digestive",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Lal Tel 140/-",
  company: "Dabur",
  mrp: 98.3,
  offerPrice: 91,
  stock: cleanStock(-3),
  unit: "Bottle",
  category: "Healthcare",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Lal Tel 75/-",
  company: "Dabur",
  mrp: 52.65,
  offerPrice: 48.75,
  stock: cleanStock(-3),
  unit: "Bottle",
  category: "Healthcare",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Red paste 10/-",
  company: "Dabur",
  mrp: 85,
  offerPrice: 78.92,
  stock: cleanStock(23),
  unit: "Tube",
  category: "Oral Care",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Red paste 48/-",
  company: "Dabur",
  mrp: 41,
  offerPrice: 37.47,
  stock: cleanStock(18),
  unit: "Tube",
  category: "Oral Care",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Red paste 6+1 20/-",
  company: "Dabur",
  mrp: 106,
  offerPrice: 99.5,
  stock: cleanStock(30),
  unit: "Tube",
  category: "Oral Care",
  minQty: 1,
  orderStep: 1,
  isFeatured: true,
},

{
  name: "Red Powder 37/-",
  company: "Dabur",
  mrp: 32,
  offerPrice: 29.37,
  stock: cleanStock(-10),
  unit: "Packet",
  category: "Oral Care",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Red Powder 99/-",
  company: "Dabur",
  mrp: 88,
  offerPrice: 83.81,
  stock: cleanStock(12),
  unit: "Packet",
  category: "Oral Care",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Sarso amla 20/-",
  company: "Dabur",
  mrp: 195,
  offerPrice: 188,
  stock: cleanStock(5),
  unit: "Bottle",
  category: "Hair Oil",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Vatika shampoo 1/-",
  company: "Dabur",
  mrp: 655,
  offerPrice: 635,
  stock: cleanStock(-0.7),
  unit: "Bottle",
  category: "Shampoo",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

// ================= REMAINING RHM =================

{
  name: "AK haldi 200g",
  company: "RHM",
  mrp: 160,
  offerPrice: 150,
  stock: cleanStock(2),
  unit: "Packet",
  category: "Masala",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "AK haldi 500g",
  company: "RHM",
  mrp: 75,
  offerPrice: 67.5,
  stock: cleanStock(20.1),
  unit: "Packet",
  category: "Masala",
  minQty: 1,
  orderStep: 1,
  isFeatured: true,
},

{
  name: "Biryani Masala 10/-",
  company: "RHM",
  mrp: 130,
  offerPrice: 118,
  stock: cleanStock(-18),
  unit: "Packet",
  category: "Masala",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Chat Masala 500g",
  company: "RHM",
  mrp: 85,
  offerPrice: 75,
  stock: cleanStock(-9),
  unit: "Packet",
  category: "Masala",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Chicken masala 10/-",
  company: "RHM",
  mrp: 130,
  offerPrice: 118,
  stock: cleanStock(-31),
  unit: "Packet",
  category: "Masala",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Chola 5/-",
  company: "RHM",
  mrp: 130,
  offerPrice: 118.74,
  stock: cleanStock(11),
  unit: "Packet",
  category: "Masala",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Chola Masala 10/-",
  company: "RHM",
  mrp: 130,
  offerPrice: 118,
  stock: cleanStock(-37),
  unit: "Packet",
  category: "Masala",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Dhaniya 5kg granded",
  company: "RHM",
  mrp: 85,
  offerPrice: 75,
  stock: cleanStock(-34.5),
  unit: "Packet",
  category: "Masala",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Garam 5/-",
  company: "RHM",
  mrp: 130,
  offerPrice: 118.74,
  stock: cleanStock(8),
  unit: "Packet",
  category: "Masala",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Garam Masala 10/-",
  company: "RHM",
  mrp: 130,
  offerPrice: 118,
  stock: cleanStock(-7),
  unit: "Packet",
  category: "Masala",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Garam sabut 10/-",
  company: "RHM",
  mrp: 175,
  offerPrice: 166.47,
  stock: cleanStock(36),
  unit: "Packet",
  category: "Masala",
  minQty: 1,
  orderStep: 1,
  isFeatured: true,
},

{
  name: "Haldi 5kg granded",
  company: "RHM",
  mrp: 150,
  offerPrice: 125,
  stock: cleanStock(-150),
  unit: "Packet",
  category: "Masala",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Jaljeera 10/-",
  company: "RHM",
  mrp: 130,
  offerPrice: 114,
  stock: cleanStock(7),
  unit: "Packet",
  category: "Drink Mix",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Khada Garam 10/-",
  company: "RHM",
  mrp: 175,
  offerPrice: 166,
  stock: cleanStock(20),
  unit: "Packet",
  category: "Masala",
  minQty: 1,
  orderStep: 1,
  isFeatured: true,
},

{
  name: "Mango powder 10/-",
  company: "RHM",
  mrp: 130,
  offerPrice: 118,
  stock: cleanStock(23),
  unit: "Packet",
  category: "Masala",
  minQty: 1,
  orderStep: 1,
  isFeatured: true,
},

{
  name: "Matar Paneer 10/-",
  company: "RHM",
  mrp: 130,
  offerPrice: 118,
  stock: cleanStock(-33),
  unit: "Packet",
  category: "Masala",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Meat 5/-",
  company: "RHM",
  mrp: 130,
  offerPrice: 118.74,
  stock: cleanStock(6),
  unit: "Packet",
  category: "Masala",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Meat Masala 10/-",
  company: "RHM",
  mrp: 130,
  offerPrice: 118,
  stock: cleanStock(19),
  unit: "Packet",
  category: "Masala",
  minQty: 1,
  orderStep: 1,
  isFeatured: true,
},

{
  name: "Mircha 5kg granded",
  company: "RHM",
  mrp: 145,
  offerPrice: 120,
  stock: cleanStock(-15),
  unit: "Packet",
  category: "Masala",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "No",
  company: "RHM",
  mrp: 206,
  offerPrice: 188.41,
  stock: cleanStock(14),
  unit: "Packet",
  category: "Masala",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Raita Masala 10/-",
  company: "RHM",
  mrp: 130,
  offerPrice: 118,
  stock: cleanStock(9),
  unit: "Packet",
  category: "Masala",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "RHM Dhaniya 10/-",
  company: "RHM",
  mrp: 105,
  offerPrice: 95,
  stock: cleanStock(-49),
  unit: "Packet",
  category: "Masala",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "RHM Dhaniya 100g 203/-",
  company: "RHM",
  mrp: 175,
  offerPrice: 155,
  stock: cleanStock(-28),
  unit: "Packet",
  category: "Masala",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "RHM Dhaniya 5/-",
  company: "RHM",
  mrp: 120,
  offerPrice: 111,
  stock: cleanStock(-3),
  unit: "Packet",
  category: "Masala",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "RHM Dhaniya 500g 161/-",
  company: "RHM",
  mrp: 140,
  offerPrice: 127.47,
  stock: cleanStock(-18),
  unit: "Packet",
  category: "Masala",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "RHM Haldi 10/-",
  company: "RHM",
  mrp: 105,
  offerPrice: 95,
  stock: cleanStock(-79),
  unit: "Packet",
  category: "Masala",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

// ================= FINAL REMAINING RHM =================

{
  name: "RHM Haldi 100g 259/-",
  company: "RHM",
  mrp: 225,
  offerPrice: 205,
  stock: cleanStock(-21),
  unit: "Packet",
  category: "Masala",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "RHM Haldi 200g 252/-",
  company: "RHM",
  mrp: 220,
  offerPrice: 199.5,
  stock: cleanStock(-65),
  unit: "Packet",
  category: "Masala",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "RHM Haldi 500g",
  company: "RHM",
  mrp: 195,
  offerPrice: 166,
  stock: cleanStock(9),
  unit: "Packet",
  category: "Masala",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "RHM Mircha 100g 299/-",
  company: "RHM",
  mrp: 258,
  offerPrice: 230,
  stock: cleanStock(-23),
  unit: "Packet",
  category: "Masala",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "RHM Mircha 200g 292/-",
  company: "RHM",
  mrp: 252,
  offerPrice: 235,
  stock: cleanStock(-26),
  unit: "Packet",
  category: "Masala",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "RHM Mircha 5/-",
  company: "RHM",
  mrp: 120,
  offerPrice: 111,
  stock: cleanStock(34),
  unit: "Packet",
  category: "Masala",
  minQty: 1,
  orderStep: 1,
  isFeatured: true,
},

{
  name: "RHM Mircha 500g 285/-",
  company: "RHM",
  mrp: 246,
  offerPrice: 225.55,
  stock: cleanStock(5),
  unit: "Packet",
  category: "Masala",
  minQty: 1,
  orderStep: 1,
  isFeatured: false,
},

{
  name: "Sabji Masala 200g",
  company: "RHM",
  mrp: 285,
  offerPrice: 260,
  stock: cleanStock(18),
  unit: "Packet",
  category: "Masala",
  minQty: 1,
  orderStep: 1,
  isFeatured: true,
},

  {
    name: "Natural Shampoo 1/-",
    company: "Patanjali Non-Food",
    mrp: 650,
    offerPrice: 632,
    stock: cleanStock(7.65),
    unit: "Bottle",
    category: "Shampoo",
    minQty: 1,
    orderStep: 1,
    isFeatured: false,
  },

];

async function importData() {
  try {
    await mongoose.connect(MONGODB_URI);

    console.log("MongoDB Connected");

    await Product.deleteMany({});

    console.log("Old Products Deleted");

    await Product.insertMany(products);

    console.log("All Products Imported Successfully");

    process.exit();

  } catch (error) {
    console.log(error);
    process.exit(1);
  }
}

importData();
